[env]
TERM = "xterm-256color"

[window]
padding.x = 0
padding.y = 0
decorations = "ButtonLess"
opacity= 1
blur = true
startup_mode = "Maximized"
option_as_alt = "Both"

[font]
size = 22

normal = { family = "FiraCode Nerd Font Mono", style = "Regular" }
bold = { family = "FiraCode Nerd Font Mono", style = "Bold" }
italic = { family = "FiraCode Nerd Font Mono", style = "Italic" }

[general]

import = [
  "~/.config/alacritty/themes/themes/rose_pine.toml",
]
